import PDFDocument from "pdfkit";

/**
 * Generate Professional Career Assessment Report PDF
 */
export const generateAssessmentPDF = async (assessment, user, analysis) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
      });

      const chunks = [];

      // Collect PDF data
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;

      // ============================================
      // PAGE 1: COVER PAGE
      // ============================================

      // Gradient-like header background (using rectangles)
      doc.rect(0, 0, pageWidth, 200).fill("#667eea");
      doc.rect(0, 150, pageWidth, 50).fill("#764ba2");

      // Logo/Title
      doc
        .fillColor("#ffffff")
        .fontSize(36)
        .font("Helvetica-Bold")
        .text("VisionRoute AI", 50, 80, { align: "center" });

      doc
        .fontSize(18)
        .font("Helvetica")
        .text("Career Assessment Report", 50, 130, { align: "center" });

      // User Info Box
      doc
        .rect(50, 250, pageWidth - 100, 150)
        .fillAndStroke("#f8f9fa", "#e0e0e0");

      doc
        .fillColor("#333333")
        .fontSize(16)
        .font("Helvetica-Bold")
        .text("Student Information", 70, 270);

      doc
        .fontSize(12)
        .font("Helvetica")
        .text(`Name: ${user.fullName || user.name || "Student"}`, 70, 300)
        .text(`Email: ${user.email}`, 70, 320)
        .text(
          `Assessment Date: ${new Date(
            assessment.completedAt
          ).toLocaleDateString()}`,
          70,
          340
        )
        .text(`Completion: ${assessment.completionPercentage}%`, 70, 360);

      // Assessment Summary Box
      if (analysis?.summary) {
        doc
          .rect(50, 420, pageWidth - 100, 100)
          .fillAndStroke("#e8f5e9", "#4caf50");

        doc
          .fillColor("#1b5e20")
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Quick Summary", 70, 440);

        doc
          .fontSize(11)
          .font("Helvetica")
          .fillColor("#2e7d32")
          .text(analysis.summary.substring(0, 200) + "...", 70, 465, {
            width: pageWidth - 140,
            align: "left",
          });
      }

      // Footer
      doc
        .fontSize(10)
        .fillColor("#999999")
        .text(
          "Generated by VisionRoute AI - Your Career Guidance Partner",
          50,
          pageHeight - 30,
          { align: "center" }
        );

      // ============================================
      // PAGE 2: RIASEC PERSONALITY PROFILE
      // ============================================
      doc.addPage();

      // Page Header
      doc.rect(0, 0, pageWidth, 60).fill("#667eea");
      doc
        .fillColor("#ffffff")
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("RIASEC Personality Profile", 50, 25);

      let yPos = 100;

      if (assessment.scores?.riasec) {
        const riasecData = assessment.scores.riasec;
        const riasecTypes = [
          { key: "realistic", label: "Realistic (Doers)", color: "#ff6b6b" },
          {
            key: "investigative",
            label: "Investigative (Thinkers)",
            color: "#4ecdc4",
          },
          { key: "artistic", label: "Artistic (Creators)", color: "#ffe66d" },
          { key: "social", label: "Social (Helpers)", color: "#95e1d3" },
          {
            key: "enterprising",
            label: "Enterprising (Persuaders)",
            color: "#f38181",
          },
          {
            key: "conventional",
            label: "Conventional (Organizers)",
            color: "#aa96da",
          },
        ];

        riasecTypes.forEach((type) => {
          const score = riasecData[type.key] || 0;
          const barWidth = Math.max(0, Math.min(400, (score / 100) * 400)) || 0;

          // Type Label
          doc
            .fillColor("#333333")
            .fontSize(12)
            .font("Helvetica-Bold")
            .text(type.label, 50, yPos);

          // Score Bar
          doc.rect(50, yPos + 18, 400, 20).fillAndStroke("#f0f0f0", "#d0d0d0");
          if (barWidth > 0) {
            doc.rect(50, yPos + 18, barWidth, 20).fill(type.color);
          }

          // Score Text
          doc
            .fillColor("#333333")
            .fontSize(11)
            .font("Helvetica")
            .text(`${score}%`, 460, yPos + 20);

          yPos += 50;
        });

        // Top 3 Types Highlight
        if (riasecData.topThreeTypes && riasecData.topThreeTypes.length > 0) {
          yPos += 20;
          doc
            .fillColor("#667eea")
            .fontSize(14)
            .font("Helvetica-Bold")
            .text("Your Dominant Personality Types:", 50, yPos);

          yPos += 25;
          riasecData.topThreeTypes.forEach((type, index) => {
            doc
              .fillColor("#333333")
              .fontSize(12)
              .font("Helvetica")
              .text(`${index + 1}. ${type}`, 70, yPos);
            yPos += 20;
          });
        }
      }

      // Page Footer
      doc
        .fontSize(9)
        .fillColor("#999999")
        .text("Page 2", pageWidth - 100, pageHeight - 30);

      // ============================================
      // PAGE 3: APTITUDE SCORES
      // ============================================
      doc.addPage();

      // Page Header
      doc.rect(0, 0, pageWidth, 60).fill("#667eea");
      doc
        .fillColor("#ffffff")
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("Aptitude & Skills Assessment", 50, 25);

      yPos = 100;

      if (assessment.scores?.aptitudes) {
        const aptitudes = assessment.scores.aptitudes;

        Object.entries(aptitudes).forEach(([skill, score]) => {
          const numScore = Number(score) || 0;
          const barWidth =
            Math.max(0, Math.min(400, (numScore / 100) * 400)) || 0;

          // Skill Label
          doc
            .fillColor("#333333")
            .fontSize(12)
            .font("Helvetica-Bold")
            .text(skill.charAt(0).toUpperCase() + skill.slice(1), 50, yPos);

          // Score Bar
          doc.rect(50, yPos + 18, 400, 20).fillAndStroke("#f0f0f0", "#d0d0d0");

          // Color based on score
          const barColor =
            numScore >= 75 ? "#4caf50" : numScore >= 50 ? "#ff9800" : "#f44336";
          if (barWidth > 0) {
            doc.rect(50, yPos + 18, barWidth, 20).fill(barColor);
          }

          // Score Text
          doc
            .fillColor("#333333")
            .fontSize(11)
            .font("Helvetica")
            .text(`${numScore}/100`, 460, yPos + 20);

          yPos += 50;

          // Add new page if needed
          if (yPos > pageHeight - 100) {
            doc.addPage();
            yPos = 50;
          }
        });
      }

      // Page Footer
      doc
        .fontSize(9)
        .fillColor("#999999")
        .text("Page 3", pageWidth - 100, pageHeight - 30);

      // ============================================
      // PAGE 4: TOP CAREER MATCHES
      // ============================================
      doc.addPage();

      // Page Header
      doc.rect(0, 0, pageWidth, 60).fill("#667eea");
      doc
        .fillColor("#ffffff")
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("Top Career Matches", 50, 25);

      yPos = 100;

      if (analysis?.careerMatches && analysis.careerMatches.length > 0) {
        analysis.careerMatches.slice(0, 10).forEach((career, index) => {
          // Career Title
          doc
            .fillColor("#667eea")
            .fontSize(14)
            .font("Helvetica-Bold")
            .text(`${index + 1}. ${career.title}`, 50, yPos);

          yPos += 20;

          // Match Percentage
          const matchPercentage = Number(career.matchPercentage) || 0;
          const matchWidth =
            Math.max(0, Math.min(200, (matchPercentage / 100) * 200)) || 0;
          doc.rect(50, yPos, 200, 15).fillAndStroke("#f0f0f0", "#d0d0d0");
          if (matchWidth > 0) {
            doc.rect(50, yPos, matchWidth, 15).fill("#4caf50");
          }
          doc
            .fillColor("#333333")
            .fontSize(10)
            .text(`${matchPercentage}% Match`, 260, yPos + 2);

          yPos += 25;

          // Description
          doc
            .fillColor("#666666")
            .fontSize(10)
            .font("Helvetica")
            .text(
              career.description?.substring(0, 150) + "..." || "",
              50,
              yPos,
              {
                width: pageWidth - 100,
              }
            );

          yPos += 40;

          // Add new page if needed
          if (yPos > pageHeight - 150) {
            doc.addPage();
            doc.rect(0, 0, pageWidth, 60).fill("#667eea");
            doc
              .fillColor("#ffffff")
              .fontSize(20)
              .font("Helvetica-Bold")
              .text("Top Career Matches (continued)", 50, 25);
            yPos = 100;
          }
        });
      }

      // Page Footer
      doc
        .fontSize(9)
        .fillColor("#999999")
        .text(`Page 4`, pageWidth - 100, pageHeight - 30);

      // ============================================
      // PAGE 5: RECOMMENDATIONS
      // ============================================
      doc.addPage();

      // Page Header
      doc.rect(0, 0, pageWidth, 60).fill("#667eea");
      doc
        .fillColor("#ffffff")
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("Recommendations & Next Steps", 50, 25);

      yPos = 100;

      // Recommended Stream
      if (analysis?.recommendedStream) {
        doc
          .fillColor("#333333")
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Recommended Stream:", 50, yPos);

        doc
          .fillColor("#667eea")
          .fontSize(16)
          .text(analysis.recommendedStream, 50, yPos + 20);

        yPos += 60;
      }

      // Next Steps
      doc
        .fillColor("#333333")
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Next Steps:", 50, yPos);

      yPos += 25;

      const nextSteps = [
        "Research your top career matches in detail",
        "Talk to professionals in these fields",
        "Explore relevant courses and certifications",
        "Build skills aligned with your chosen path",
        "Consult with our AI Career Counselor for guidance",
        "Review entrance exam requirements",
        "Plan your academic roadmap",
      ];

      nextSteps.forEach((step, index) => {
        doc
          .fillColor("#333333")
          .fontSize(11)
          .font("Helvetica")
          .text(`${index + 1}. ${step}`, 70, yPos);
        yPos += 25;
      });

      // Footer Box
      yPos = pageHeight - 100;
      doc
        .rect(50, yPos, pageWidth - 100, 60)
        .fillAndStroke("#e3f2fd", "#2196f3");

      doc
        .fillColor("#1976d2")
        .fontSize(12)
        .font("Helvetica-Bold")
        .text("Need More Guidance?", 70, yPos + 15);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(
          "Chat with our AI Career Counselor at VisionRoute AI",
          70,
          yPos + 35
        );

      // Final Page Footer
      doc
        .fontSize(9)
        .fillColor("#999999")
        .text("Page 5", pageWidth - 100, pageHeight - 30);

      // Finalize PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export default {
  generateAssessmentPDF,
};
