// Part 2: Aptitude (25 questions), Personality (20 questions), Academic (20 questions)
// This file contains questions 21-85 to be merged with part 1

export const aptitudeQuestions = [
  // ==================== APTITUDE QUESTIONS (25) ====================
  {
    questionText: "How quickly can you solve mathematical word problems?",
    category: "aptitude",
    subcategory: "Numerical",
    questionType: "rating_scale",
    options: [
      { text: "Very slowly", value: 1, score: 20 },
      { text: "Slowly", value: 2, score: 40 },
      { text: "Average speed", value: 3, score: 60 },
      { text: "Quickly", value: 4, score: 80 },
      { text: "Very quickly", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "numerical",
    maxScore: 100,
    order: 21,
    isRequired: true,
    helpText:
      "Consider your speed in solving algebra, geometry, or arithmetic problems.",
  },
  {
    questionText:
      "How good are you at understanding complex written instructions?",
    category: "aptitude",
    subcategory: "Verbal",
    questionType: "rating_scale",
    options: [
      { text: "Poor", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Good", value: 4, score: 80 },
      { text: "Excellent", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "verbal",
    maxScore: 100,
    order: 22,
    isRequired: true,
  },
  {
    questionText: "Can you easily visualize 3D objects from 2D drawings?",
    category: "aptitude",
    subcategory: "Spatial",
    questionType: "rating_scale",
    options: [
      { text: "Not at all", value: 1, score: 20 },
      { text: "With difficulty", value: 2, score: 40 },
      { text: "Somewhat", value: 3, score: 60 },
      { text: "Easily", value: 4, score: 80 },
      { text: "Very easily", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "spatial",
    maxScore: 100,
    order: 23,
    isRequired: true,
  },
  {
    questionText:
      "How well can you identify patterns in sequences of numbers or shapes?",
    category: "aptitude",
    subcategory: "Abstract Reasoning",
    questionType: "rating_scale",
    options: [
      { text: "Poorly", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Well", value: 4, score: 80 },
      { text: "Very well", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "abstract",
    maxScore: 100,
    order: 24,
    isRequired: true,
  },
  {
    questionText:
      "How quickly can you learn and apply new software or technology?",
    category: "aptitude",
    subcategory: "Technical",
    questionType: "rating_scale",
    options: [
      { text: "Very slowly", value: 1, score: 20 },
      { text: "Slowly", value: 2, score: 40 },
      { text: "At average pace", value: 3, score: 60 },
      { text: "Quickly", value: 4, score: 80 },
      { text: "Very quickly", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "technical",
    maxScore: 100,
    order: 25,
    isRequired: true,
  },
  {
    questionText: "How good are you at remembering facts, dates, and details?",
    category: "aptitude",
    subcategory: "Memory",
    questionType: "rating_scale",
    options: [
      { text: "Poor", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Good", value: 4, score: 80 },
      { text: "Excellent", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "memory",
    maxScore: 100,
    order: 26,
    isRequired: true,
  },
  {
    questionText: "Can you solve logical puzzles and brain teasers easily?",
    category: "aptitude",
    subcategory: "Logical Reasoning",
    questionType: "rating_scale",
    options: [
      { text: "Not at all", value: 1, score: 20 },
      { text: "With great difficulty", value: 2, score: 40 },
      { text: "With some effort", value: 3, score: 60 },
      { text: "Fairly easily", value: 4, score: 80 },
      { text: "Very easily", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "logical",
    maxScore: 100,
    order: 27,
    isRequired: true,
  },
  {
    questionText: "How well can you analyze data and draw conclusions?",
    category: "aptitude",
    subcategory: "Analytical",
    questionType: "rating_scale",
    options: [
      { text: "Poorly", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Well", value: 4, score: 80 },
      { text: "Very well", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "analytical",
    maxScore: 100,
    order: 28,
    isRequired: true,
  },
  {
    questionText: "How good are you at expressing your ideas in writing?",
    category: "aptitude",
    subcategory: "Verbal",
    questionType: "rating_scale",
    options: [
      { text: "Poor", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Good", value: 4, score: 80 },
      { text: "Excellent", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "verbal",
    maxScore: 100,
    order: 29,
    isRequired: true,
  },
  {
    questionText: "Can you calculate percentages and ratios mentally?",
    category: "aptitude",
    subcategory: "Numerical",
    questionType: "rating_scale",
    options: [
      { text: "Not at all", value: 1, score: 20 },
      { text: "With difficulty", value: 2, score: 40 },
      { text: "Sometimes", value: 3, score: 60 },
      { text: "Usually", value: 4, score: 80 },
      { text: "Always easily", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "numerical",
    maxScore: 100,
    order: 30,
    isRequired: true,
  },
  {
    questionText:
      "How well can you understand and interpret graphs and charts?",
    category: "aptitude",
    subcategory: "Data Interpretation",
    questionType: "rating_scale",
    options: [
      { text: "Poorly", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Well", value: 4, score: 80 },
      { text: "Very well", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "analytical",
    maxScore: 100,
    order: 31,
    isRequired: true,
  },
  {
    questionText:
      "How good are you at debugging code or troubleshooting technical problems?",
    category: "aptitude",
    subcategory: "Technical",
    questionType: "rating_scale",
    options: [
      { text: "Poor", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Good", value: 4, score: 80 },
      { text: "Excellent", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "technical",
    maxScore: 100,
    order: 32,
    isRequired: true,
  },
  {
    questionText: "Can you easily understand cause-and-effect relationships?",
    category: "aptitude",
    subcategory: "Logical Reasoning",
    questionType: "rating_scale",
    options: [
      { text: "Not at all", value: 1, score: 20 },
      { text: "With difficulty", value: 2, score: 40 },
      { text: "Somewhat", value: 3, score: 60 },
      { text: "Easily", value: 4, score: 80 },
      { text: "Very easily", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "logical",
    maxScore: 100,
    order: 33,
    isRequired: true,
  },
  {
    questionText:
      "How well can you visualize how objects fit together or move in space?",
    category: "aptitude",
    subcategory: "Spatial",
    questionType: "rating_scale",
    options: [
      { text: "Poorly", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Well", value: 4, score: 80 },
      { text: "Very well", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "spatial",
    maxScore: 100,
    order: 34,
    isRequired: true,
  },
  {
    questionText: "How good are you at finding creative solutions to problems?",
    category: "aptitude",
    subcategory: "Creative Thinking",
    questionType: "rating_scale",
    options: [
      { text: "Poor", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Good", value: 4, score: 80 },
      { text: "Excellent", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "creative",
    maxScore: 100,
    order: 35,
    isRequired: true,
  },
  {
    questionText:
      "Can you work with fractions, decimals, and algebraic equations comfortably?",
    category: "aptitude",
    subcategory: "Numerical",
    questionType: "rating_scale",
    options: [
      { text: "Not at all", value: 1, score: 20 },
      { text: "With difficulty", value: 2, score: 40 },
      { text: "Somewhat", value: 3, score: 60 },
      { text: "Comfortably", value: 4, score: 80 },
      { text: "Very comfortably", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "numerical",
    maxScore: 100,
    order: 36,
    isRequired: true,
  },
  {
    questionText:
      "How well can you comprehend and summarize lengthy articles or books?",
    category: "aptitude",
    subcategory: "Verbal",
    questionType: "rating_scale",
    options: [
      { text: "Poorly", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Well", value: 4, score: 80 },
      { text: "Very well", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "verbal",
    maxScore: 100,
    order: 37,
    isRequired: true,
  },
  {
    questionText:
      "How good are you at identifying errors or inconsistencies in information?",
    category: "aptitude",
    subcategory: "Attention to Detail",
    questionType: "rating_scale",
    options: [
      { text: "Poor", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Good", value: 4, score: 80 },
      { text: "Excellent", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "attention",
    maxScore: 100,
    order: 38,
    isRequired: true,
  },
  {
    questionText:
      "Can you think of multiple ways to approach a single problem?",
    category: "aptitude",
    subcategory: "Creative Thinking",
    questionType: "rating_scale",
    options: [
      { text: "Rarely", value: 1, score: 20 },
      { text: "Occasionally", value: 2, score: 40 },
      { text: "Sometimes", value: 3, score: 60 },
      { text: "Often", value: 4, score: 80 },
      { text: "Always", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "creative",
    maxScore: 100,
    order: 39,
    isRequired: true,
  },
  {
    questionText: "How well can you understand and use scientific terminology?",
    category: "aptitude",
    subcategory: "Technical",
    questionType: "rating_scale",
    options: [
      { text: "Poorly", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Well", value: 4, score: 80 },
      { text: "Very well", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "technical",
    maxScore: 100,
    order: 40,
    isRequired: true,
  },
  {
    questionText:
      "How good are you at making decisions based on incomplete information?",
    category: "aptitude",
    subcategory: "Analytical",
    questionType: "rating_scale",
    options: [
      { text: "Poor", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Good", value: 4, score: 80 },
      { text: "Excellent", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "analytical",
    maxScore: 100,
    order: 41,
    isRequired: true,
  },
  {
    questionText:
      "Can you rotate objects mentally and predict how they would look from different angles?",
    category: "aptitude",
    subcategory: "Spatial",
    questionType: "rating_scale",
    options: [
      { text: "Not at all", value: 1, score: 20 },
      { text: "With difficulty", value: 2, score: 40 },
      { text: "Somewhat", value: 3, score: 60 },
      { text: "Easily", value: 4, score: 80 },
      { text: "Very easily", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "spatial",
    maxScore: 100,
    order: 42,
    isRequired: true,
  },
  {
    questionText:
      "How well can you identify assumptions and biases in arguments?",
    category: "aptitude",
    subcategory: "Critical Thinking",
    questionType: "rating_scale",
    options: [
      { text: "Poorly", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Well", value: 4, score: 80 },
      { text: "Very well", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "critical",
    maxScore: 100,
    order: 43,
    isRequired: true,
  },
  {
    questionText:
      "How good are you at following multi-step procedures accurately?",
    category: "aptitude",
    subcategory: "Attention to Detail",
    questionType: "rating_scale",
    options: [
      { text: "Poor", value: 1, score: 20 },
      { text: "Below average", value: 2, score: 40 },
      { text: "Average", value: 3, score: 60 },
      { text: "Good", value: 4, score: 80 },
      { text: "Excellent", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "attention",
    maxScore: 100,
    order: 44,
    isRequired: true,
  },
  {
    questionText:
      "Can you evaluate the strength of evidence supporting different viewpoints?",
    category: "aptitude",
    subcategory: "Critical Thinking",
    questionType: "rating_scale",
    options: [
      { text: "Not at all", value: 1, score: 20 },
      { text: "With difficulty", value: 2, score: 40 },
      { text: "Somewhat", value: 3, score: 60 },
      { text: "Well", value: 4, score: 80 },
      { text: "Very well", value: 5, score: 100 },
    ],
    scoringType: "aptitude",
    scoringKey: "critical",
    maxScore: 100,
    order: 45,
    isRequired: true,
  },
];

export const personalityQuestions = [
  // ==================== PERSONALITY QUESTIONS (20) - Big Five ====================
  {
    questionText:
      "I am usually the life of the party and enjoy being the center of attention.",
    category: "personality",
    subcategory: "Extraversion",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "extraversion",
    maxScore: 100,
    order: 46,
    isRequired: true,
  },
  {
    questionText: "I am always prepared and pay attention to details.",
    category: "personality",
    subcategory: "Conscientiousness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "conscientiousness",
    maxScore: 100,
    order: 47,
    isRequired: true,
  },
  {
    questionText: "I get stressed out easily and worry about things.",
    category: "personality",
    subcategory: "Neuroticism",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 100 },
      { text: "Disagree", value: 2, score: 75 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 25 },
      { text: "Strongly agree", value: 5, score: 0 },
    ],
    scoringType: "big_five",
    scoringKey: "emotional_stability",
    maxScore: 100,
    order: 48,
    isRequired: true,
    helpText:
      "Higher score indicates emotional stability (inverse of neuroticism).",
  },
  {
    questionText: "I feel comfortable around people and make friends easily.",
    category: "personality",
    subcategory: "Agreeableness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "agreeableness",
    maxScore: 100,
    order: 49,
    isRequired: true,
  },
  {
    questionText: "I have a vivid imagination and enjoy abstract ideas.",
    category: "personality",
    subcategory: "Openness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "openness",
    maxScore: 100,
    order: 50,
    isRequired: true,
  },
  {
    questionText:
      "I prefer quiet, solitary activities over large social gatherings.",
    category: "personality",
    subcategory: "Extraversion",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 100 },
      { text: "Disagree", value: 2, score: 75 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 25 },
      { text: "Strongly agree", value: 5, score: 0 },
    ],
    scoringType: "big_five",
    scoringKey: "extraversion",
    maxScore: 100,
    order: 51,
    isRequired: true,
    helpText: "Reverse scored - disagreement indicates extraversion.",
  },
  {
    questionText:
      "I often procrastinate and find it hard to stick to a schedule.",
    category: "personality",
    subcategory: "Conscientiousness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 100 },
      { text: "Disagree", value: 2, score: 75 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 25 },
      { text: "Strongly agree", value: 5, score: 0 },
    ],
    scoringType: "big_five",
    scoringKey: "conscientiousness",
    maxScore: 100,
    order: 52,
    isRequired: true,
    helpText: "Reverse scored.",
  },
  {
    questionText: "I remain calm under pressure and rarely feel anxious.",
    category: "personality",
    subcategory: "Neuroticism",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "emotional_stability",
    maxScore: 100,
    order: 53,
    isRequired: true,
  },
  {
    questionText:
      "I trust others easily and believe people have good intentions.",
    category: "personality",
    subcategory: "Agreeableness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "agreeableness",
    maxScore: 100,
    order: 54,
    isRequired: true,
  },
  {
    questionText:
      "I prefer routine and familiar experiences over new adventures.",
    category: "personality",
    subcategory: "Openness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 100 },
      { text: "Disagree", value: 2, score: 75 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 25 },
      { text: "Strongly agree", value: 5, score: 0 },
    ],
    scoringType: "big_five",
    scoringKey: "openness",
    maxScore: 100,
    order: 55,
    isRequired: true,
    helpText: "Reverse scored.",
  },
  {
    questionText: "I take charge in group situations and enjoy leading others.",
    category: "personality",
    subcategory: "Extraversion",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "extraversion",
    maxScore: 100,
    order: 56,
    isRequired: true,
  },
  {
    questionText: "I set clear goals and work systematically to achieve them.",
    category: "personality",
    subcategory: "Conscientiousness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "conscientiousness",
    maxScore: 100,
    order: 57,
    isRequired: true,
  },
  {
    questionText: "I often feel overwhelmed by emotions and have mood swings.",
    category: "personality",
    subcategory: "Neuroticism",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 100 },
      { text: "Disagree", value: 2, score: 75 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 25 },
      { text: "Strongly agree", value: 5, score: 0 },
    ],
    scoringType: "big_five",
    scoringKey: "emotional_stability",
    maxScore: 100,
    order: 58,
    isRequired: true,
    helpText: "Reverse scored.",
  },
  {
    questionText:
      "I am considerate of others' feelings and try to help when I can.",
    category: "personality",
    subcategory: "Agreeableness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "agreeableness",
    maxScore: 100,
    order: 59,
    isRequired: true,
  },
  {
    questionText:
      "I enjoy learning new things and exploring different perspectives.",
    category: "personality",
    subcategory: "Openness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "openness",
    maxScore: 100,
    order: 60,
    isRequired: true,
  },
  {
    questionText:
      "I can be blunt and direct, even if it hurts others' feelings.",
    category: "personality",
    subcategory: "Agreeableness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 100 },
      { text: "Disagree", value: 2, score: 75 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 25 },
      { text: "Strongly agree", value: 5, score: 0 },
    ],
    scoringType: "big_five",
    scoringKey: "agreeableness",
    maxScore: 100,
    order: 61,
    isRequired: true,
    helpText: "Reverse scored.",
  },
  {
    questionText: "I am organized and like to keep things tidy and in order.",
    category: "personality",
    subcategory: "Conscientiousness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "conscientiousness",
    maxScore: 100,
    order: 62,
    isRequired: true,
  },
  {
    questionText:
      "I enjoy trying new foods, traveling to new places, and experiencing different cultures.",
    category: "personality",
    subcategory: "Openness",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "openness",
    maxScore: 100,
    order: 63,
    isRequired: true,
  },
  {
    questionText: "I talk to a lot of different people at social events.",
    category: "personality",
    subcategory: "Extraversion",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "extraversion",
    maxScore: 100,
    order: 64,
    isRequired: true,
  },
  {
    questionText: "I handle stress well and bounce back quickly from setbacks.",
    category: "personality",
    subcategory: "Neuroticism",
    questionType: "rating_scale",
    options: [
      { text: "Strongly disagree", value: 1, score: 0 },
      { text: "Disagree", value: 2, score: 25 },
      { text: "Neutral", value: 3, score: 50 },
      { text: "Agree", value: 4, score: 75 },
      { text: "Strongly agree", value: 5, score: 100 },
    ],
    scoringType: "big_five",
    scoringKey: "emotional_stability",
    maxScore: 100,
    order: 65,
    isRequired: true,
  },
];

export const academicQuestions = [
  // ==================== ACADEMIC PERFORMANCE QUESTIONS (20) ====================
  {
    questionText: "How would you rate your overall performance in Mathematics?",
    category: "academic",
    subcategory: "Mathematics",
    questionType: "rating_scale",
    options: [
      { text: "Below 50%", value: 1, score: 20 },
      { text: "50-60%", value: 2, score: 40 },
      { text: "60-75%", value: 3, score: 60 },
      { text: "75-85%", value: 4, score: 80 },
      { text: "Above 85%", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "mathematics",
    maxScore: 100,
    order: 66,
    isRequired: true,
  },
  {
    questionText:
      "How would you rate your overall performance in Science (Physics, Chemistry, Biology)?",
    category: "academic",
    subcategory: "Science",
    questionType: "rating_scale",
    options: [
      { text: "Below 50%", value: 1, score: 20 },
      { text: "50-60%", value: 2, score: 40 },
      { text: "60-75%", value: 3, score: 60 },
      { text: "75-85%", value: 4, score: 80 },
      { text: "Above 85%", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "science",
    maxScore: 100,
    order: 67,
    isRequired: true,
  },
  {
    questionText:
      "How would you rate your performance in English/Language subjects?",
    category: "academic",
    subcategory: "Languages",
    questionType: "rating_scale",
    options: [
      { text: "Below 50%", value: 1, score: 20 },
      { text: "50-60%", value: 2, score: 40 },
      { text: "60-75%", value: 3, score: 60 },
      { text: "75-85%", value: 4, score: 80 },
      { text: "Above 85%", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "languages",
    maxScore: 100,
    order: 68,
    isRequired: true,
  },
  {
    questionText:
      "How would you rate your performance in Social Studies/Humanities?",
    category: "academic",
    subcategory: "Social Studies",
    questionType: "rating_scale",
    options: [
      { text: "Below 50%", value: 1, score: 20 },
      { text: "50-60%", value: 2, score: 40 },
      { text: "60-75%", value: 3, score: 60 },
      { text: "75-85%", value: 4, score: 80 },
      { text: "Above 85%", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "social_studies",
    maxScore: 100,
    order: 69,
    isRequired: true,
  },
  {
    questionText: "Which subject do you find most interesting?",
    category: "academic",
    subcategory: "Subject Interest",
    questionType: "multiple_choice",
    options: [
      { text: "Mathematics", value: "math", score: 0 },
      { text: "Physics", value: "physics", score: 0 },
      { text: "Chemistry", value: "chemistry", score: 0 },
      { text: "Biology", value: "biology", score: 0 },
      { text: "Computer Science", value: "computer", score: 0 },
      { text: "English/Literature", value: "english", score: 0 },
      { text: "History", value: "history", score: 0 },
      { text: "Economics", value: "economics", score: 0 },
      { text: "Arts/Music", value: "arts", score: 0 },
      { text: "Physical Education", value: "pe", score: 0 },
    ],
    scoringType: "preference",
    scoringKey: "favorite_subject",
    maxScore: 0,
    order: 70,
    isRequired: true,
    helpText: "This helps us understand your natural inclination.",
  },
  {
    questionText: "Which subject do you find most challenging or difficult?",
    category: "academic",
    subcategory: "Subject Difficulty",
    questionType: "multiple_choice",
    options: [
      { text: "Mathematics", value: "math", score: 0 },
      { text: "Physics", value: "physics", score: 0 },
      { text: "Chemistry", value: "chemistry", score: 0 },
      { text: "Biology", value: "biology", score: 0 },
      { text: "Computer Science", value: "computer", score: 0 },
      { text: "English/Literature", value: "english", score: 0 },
      { text: "History", value: "history", score: 0 },
      { text: "Economics", value: "economics", score: 0 },
      { text: "Arts/Music", value: "arts", score: 0 },
      { text: "Physical Education", value: "pe", score: 0 },
    ],
    scoringType: "preference",
    scoringKey: "difficult_subject",
    maxScore: 0,
    order: 71,
    isRequired: true,
  },
  {
    questionText:
      "How much time do you typically spend on homework and self-study daily?",
    category: "academic",
    subcategory: "Study Habits",
    questionType: "multiple_choice",
    options: [
      { text: "Less than 30 minutes", value: "1", score: 20 },
      { text: "30 minutes to 1 hour", value: "2", score: 40 },
      { text: "1 to 2 hours", value: "3", score: 60 },
      { text: "2 to 3 hours", value: "4", score: 80 },
      { text: "More than 3 hours", value: "5", score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "study_time",
    maxScore: 100,
    order: 72,
    isRequired: true,
  },
  {
    questionText:
      "Do you participate in any extracurricular activities related to academics? (Science club, Math olympiad, Debate, etc.)",
    category: "academic",
    subcategory: "Extra Activities",
    questionType: "yes_no",
    options: [
      { text: "Yes, regularly", value: "yes_regular", score: 100 },
      { text: "Yes, occasionally", value: "yes_occasional", score: 60 },
      { text: "No", value: "no", score: 20 },
    ],
    scoringType: "academic",
    scoringKey: "extracurricular",
    maxScore: 100,
    order: 73,
    isRequired: true,
  },
  {
    questionText: "Have you received any awards or recognition in academics?",
    category: "academic",
    subcategory: "Achievements",
    questionType: "yes_no",
    options: [
      { text: "Yes, multiple times", value: "yes_multiple", score: 100 },
      { text: "Yes, once or twice", value: "yes_few", score: 60 },
      { text: "No", value: "no", score: 20 },
    ],
    scoringType: "academic",
    scoringKey: "achievements",
    maxScore: 100,
    order: 74,
    isRequired: true,
  },
  {
    questionText:
      "How confident are you in your ability to learn new academic concepts?",
    category: "academic",
    subcategory: "Learning Confidence",
    questionType: "rating_scale",
    options: [
      { text: "Not confident", value: 1, score: 20 },
      { text: "Slightly confident", value: 2, score: 40 },
      { text: "Moderately confident", value: 3, score: 60 },
      { text: "Very confident", value: 4, score: 80 },
      { text: "Extremely confident", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "learning_confidence",
    maxScore: 100,
    order: 75,
    isRequired: true,
  },
  {
    questionText:
      "Do you prefer practical/hands-on learning or theoretical/book learning?",
    category: "academic",
    subcategory: "Learning Style",
    questionType: "multiple_choice",
    options: [
      {
        text: "Strongly prefer practical",
        value: "practical_strong",
        score: 0,
      },
      { text: "Prefer practical", value: "practical", score: 0 },
      { text: "Neutral/Both equally", value: "neutral", score: 0 },
      { text: "Prefer theoretical", value: "theoretical", score: 0 },
      {
        text: "Strongly prefer theoretical",
        value: "theoretical_strong",
        score: 0,
      },
    ],
    scoringType: "preference",
    scoringKey: "learning_style",
    maxScore: 0,
    order: 76,
    isRequired: true,
  },
  {
    questionText:
      "How would you rate your performance in Computer Science/IT (if applicable)?",
    category: "academic",
    subcategory: "Technology",
    questionType: "rating_scale",
    options: [
      { text: "Not applicable/Not taken", value: 0, score: 50 },
      { text: "Below 50%", value: 1, score: 20 },
      { text: "50-60%", value: 2, score: 40 },
      { text: "60-75%", value: 3, score: 60 },
      { text: "75-85%", value: 4, score: 80 },
      { text: "Above 85%", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "computer_science",
    maxScore: 100,
    order: 77,
    isRequired: true,
  },
  {
    questionText: "Do you enjoy group projects and collaborative learning?",
    category: "academic",
    subcategory: "Learning Preference",
    questionType: "rating_scale",
    options: [
      { text: "Not at all", value: 1, score: 20 },
      { text: "Not really", value: 2, score: 40 },
      { text: "Neutral", value: 3, score: 60 },
      { text: "Yes, somewhat", value: 4, score: 80 },
      { text: "Yes, very much", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "collaborative_learning",
    maxScore: 100,
    order: 78,
    isRequired: true,
  },
  {
    questionText: "How do you perform under exam pressure?",
    category: "academic",
    subcategory: "Exam Performance",
    questionType: "rating_scale",
    options: [
      { text: "Poorly - I panic", value: 1, score: 20 },
      { text: "Below my usual ability", value: 2, score: 40 },
      { text: "About the same as usual", value: 3, score: 60 },
      { text: "Better than usual", value: 4, score: 80 },
      { text: "Excellent - I thrive under pressure", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "exam_performance",
    maxScore: 100,
    order: 79,
    isRequired: true,
  },
  {
    questionText:
      "Have you taken any additional courses or coaching outside school?",
    category: "academic",
    subcategory: "Additional Learning",
    questionType: "yes_no",
    options: [
      { text: "Yes, multiple subjects", value: "yes_multiple", score: 100 },
      { text: "Yes, one subject", value: "yes_one", score: 60 },
      { text: "No", value: "no", score: 20 },
    ],
    scoringType: "academic",
    scoringKey: "additional_courses",
    maxScore: 100,
    order: 80,
    isRequired: true,
  },
  {
    questionText:
      "Which stream are you currently most interested in pursuing after 10th grade?",
    category: "academic",
    subcategory: "Stream Preference",
    questionType: "multiple_choice",
    options: [
      {
        text: "Science (PCM - Physics, Chemistry, Math)",
        value: "pcm",
        score: 0,
      },
      {
        text: "Science (PCB - Physics, Chemistry, Biology)",
        value: "pcb",
        score: 0,
      },
      { text: "Commerce with Math", value: "commerce_math", score: 0 },
      { text: "Commerce without Math", value: "commerce", score: 0 },
      { text: "Arts/Humanities", value: "arts", score: 0 },
      { text: "Vocational/Technical", value: "vocational", score: 0 },
      { text: "Not sure yet", value: "unsure", score: 0 },
    ],
    scoringType: "preference",
    scoringKey: "stream_preference",
    maxScore: 0,
    order: 81,
    isRequired: true,
    helpText:
      "This is just your current preference - our assessment will help confirm or guide this choice.",
  },
  {
    questionText:
      "How important are career prospects and salary potential in your stream choice?",
    category: "academic",
    subcategory: "Career Motivation",
    questionType: "rating_scale",
    options: [
      { text: "Not important at all", value: 1, score: 20 },
      { text: "Slightly important", value: 2, score: 40 },
      { text: "Moderately important", value: 3, score: 60 },
      { text: "Very important", value: 4, score: 80 },
      { text: "Extremely important", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "career_focus",
    maxScore: 100,
    order: 82,
    isRequired: true,
  },
  {
    questionText: "Do you have a specific career goal in mind?",
    category: "academic",
    subcategory: "Career Goal",
    questionType: "yes_no",
    options: [
      { text: "Yes, very clear goal", value: "yes_clear", score: 100 },
      { text: "Yes, some ideas", value: "yes_some", score: 60 },
      { text: "No, not sure", value: "no", score: 20 },
    ],
    scoringType: "academic",
    scoringKey: "career_clarity",
    maxScore: 100,
    order: 83,
    isRequired: true,
  },
  {
    questionText:
      "How supportive is your family regarding your academic and career choices?",
    category: "academic",
    subcategory: "Family Support",
    questionType: "rating_scale",
    options: [
      { text: "Not supportive", value: 1, score: 20 },
      { text: "Slightly supportive", value: 2, score: 40 },
      { text: "Moderately supportive", value: 3, score: 60 },
      { text: "Very supportive", value: 4, score: 80 },
      { text: "Extremely supportive", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "family_support",
    maxScore: 100,
    order: 84,
    isRequired: true,
  },
  {
    questionText:
      "Are you willing to work hard and dedicate significant time to achieve your academic goals?",
    category: "academic",
    subcategory: "Commitment",
    questionType: "rating_scale",
    options: [
      { text: "Not really", value: 1, score: 20 },
      { text: "Somewhat willing", value: 2, score: 40 },
      { text: "Moderately willing", value: 3, score: 60 },
      { text: "Very willing", value: 4, score: 80 },
      { text: "Absolutely committed", value: 5, score: 100 },
    ],
    scoringType: "academic",
    scoringKey: "commitment",
    maxScore: 100,
    order: 85,
    isRequired: true,
  },
];
